if __name__ == '__main__':
    x0 = input()
    x1 = input()
    x2 = input()
    x3 = input()
    x0_bytearray = bytearray.fromhex(x0)
    x1_bytearray = bytearray.fromhex(x1)
    x2_bytearray = bytearray.fromhex(x2)
    x3_bytearray = bytearray.fromhex(x3)
    x0_bytearray.reverse()
    x1_bytearray.reverse()
    x2_bytearray.reverse()
    x3_bytearray.reverse()
    print(x0_bytearray.hex(), x1_bytearray.hex(), x2_bytearray.hex(), x3_bytearray.hex())
